### PR TITLE
Fix ekhaled/f3-cortex-model-generator#1: Exclude views

### PR DESCRIPTION
**Pull request by kumy**

### CODE REVIEW

**Comment by ekhaled** [comment]
Thank you very much for the pull request.
I would like to make views ignorable behind a config flag, rather than universally.

As far as I can tell `SHOW CREATE TABLE` works for view too... I use it all the time and MySQL website says so too https://dev.mysql.com/doc/refman/5.6/en/show-create-table.html

Is this not what you are experiencing? does it really crash?
What MySQL version are you using?

**Comment by kumy** [comment]
Sorry to have provided enough debug outputs

Yes it crash like this:

```
php ./generator.php 
SHOW CREATE TABLE `gk-aktywnekody`
[..]
SHOW CREATE TABLE `test`
PHP Fatal error:  Uncaught Error: Call to a member function fetchAll() on boolean in /home/kumy/GIT/cortex-generator/vendor/ekhaled/schema-parser-mysql/src/Ekhaled/MysqlSchema/Parser.php:88
Stack trace:
#0 /home/kumy/GIT/cortex-generator/vendor/ekhaled/f3-cortex-model-generator/src/Ekhaled/Generators/MySQL/Model.php(175): Ekhaled\MysqlSchema\Parser->getSchema()
#1 /home/kumy/GIT/cortex-generator/vendor/ekhaled/f3-cortex-model-generator/src/Ekhaled/Generators/MySQL/Model.php(49): Ekhaled\Generators\MySQL\Model->getSchema()
#2 /home/kumy/GIT/cortex-generator/generator.php(15): Ekhaled\Generators\MySQL\Model->generate()
#3 {main}
  thrown in /home/kumy/GIT/cortex-generator/vendor/ekhaled/schema-parser-mysql/src/Ekhaled/MysqlSchema/Parser.php on line 88
```

`test` is a view.

```
mysql -V
mysql  Ver 15.1 Distrib 10.1.13-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
```

```
SHOW CREATE TABLE `test`;
ERROR 1142 (42000): SHOW VIEW command denied to user 'geokrety'@'localhost' for table 'test'
```

Oh! This user just doesn't have necessary privileges to show the create view statement!

Feel free to close, and thanks for the input :)

**Comment by ekhaled** [comment]
No problem,
I will still push an update with the ability to exclude views, will let you know here when done.

**Comment by ekhaled** [comment]
done 😃 

please see https://github.com/ekhaled/f3-cortex-model-generator/commit/456512c4664bceb820e06572c039b325738a5394 for docs on new options

**Comment by kumy** [comment]
Thanks

**Pull request closed without merging**
